services:
  app:
    image: gandonov2/student-registry-app:latest
    ports:
      - "8081:8081" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=development
